Repository snek-at/intel, pull requests merged in 2020-05, with the labels that each got.

#51 Intel quicky 2 to implement 1
  src/index.ts
  src/reducer/database/osm/models.ts
  src/reducer/database/osm/reconstructor.ts
  src/reducer/helper/profile.ts
  src/reducer/helper/statistic.ts
  src/reducer/index.ts
  src/toolbox/Delay.ts
  src/utils/github/converter.ts
  src/utils/gitlab/converter.ts
  src/utils/oauth/GithubProvider.ts
  src/utils/oauth/config.json
Labels: bug

#58 Add utils gitlab 2 to implement 1
  src/utils/gitlab/paths.ts
Labels: bug

#56 Add talks 1 to implement 1
  src/index.ts
  src/reducer/database/models.ts
  src/reducer/database/osm/models.ts
  src/reducer/database/osm/statements/talk.ts
  src/reducer/helper/index.ts
  src/reducer/helper/talks.ts
  src/reducer/index.ts
  src/utils/talks/converter.ts
  src/utils/talks/index.ts
  src/utils/talks/paths.ts
  src/utils/upload/anonfiles.ts
  src/utils/upload/index.ts
Labels: enhancement

#61 Intel quicky 3 to implement 1
  package.json
  src/index.ts
  tsconfig.json
Labels: enhancement, invalid

#66 Improve intel 1 to implement 1
  src/index.ts
  src/reducer/database/models.ts
  src/reducer/database/osm/index.ts
  src/reducer/database/osm/models.ts
  src/reducer/database/osm/reconstructor.ts
  src/reducer/database/osm/statements/calendar.ts
  src/reducer/database/osm/statements/contribution.ts
  src/reducer/database/osm/statements/language.ts
  src/reducer/database/osm/statements/member.ts
  src/reducer/database/osm/statements/organization.ts
  src/reducer/database/osm/statements/organizationHasMember.ts
  src/reducer/database/osm/statements/platform.ts
  src/reducer/database/osm/statements/platformHasOrganization.ts
  src/reducer/database/osm/statements/platformHasRepository.ts
  src/reducer/database/osm/statements/repository.ts
  src/reducer/database/osm/statements/repositoryHasMember.ts
  src/reducer/database/osm/statements/statistic.ts
  src/reducer/database/osm/statements/streak.ts
  src/reducer/database/osm/statements/talk.ts
  src/reducer/helper/statistic.ts
  src/reducer/index.ts
  src/utils/github/converter.ts
  src/utils/gitlab/converter.ts
  src/utils/talks/index.ts
  src/utils/upload/anonfiles.ts
Labels: enhancement

#71 Update pr template a1 to master
  PULL_REQUEST_TEMPLATE
Labels: documentation

#74 Improve intel 2 to implement 1
  src/index.ts
  src/reducer/database/osm/statements/repository.ts
  src/utils/oauth/GithubProvider.ts
Labels: bug, enhancement, invalid

#69 Improve documentation 1 to implement 1
  .vscode/settings.json
  src/index.ts
  src/reducer/database/helper/calendar.ts
  src/reducer/database/helper/general.ts
  src/reducer/database/helper/statistic.ts
  src/reducer/database/models.ts
  src/reducer/database/osm/index.ts
  src/reducer/database/osm/models.ts
  src/reducer/database/osm/reconstructor.ts
  src/reducer/helper/calendar.ts
  src/reducer/helper/language.ts
  src/reducer/helper/profile.ts
  src/reducer/helper/statistic.ts
  src/reducer/helper/talks.ts
  src/reducer/index.ts
  src/toolbox/Delay.ts
  src/toolbox/GuidGenerator.ts
  src/utils/github/converter.ts
  src/utils/github/queries/index.ts
  src/utils/gitlab/converter.ts
  src/utils/gitlab/paths.ts
  src/utils/oauth/GithubProvider.ts
  src/utils/oauth/index.ts
  src/utils/talks/index.ts
  src/utils/upload/anonfiles.ts
Labels: documentation
