Repository snek-at/intel, pull requests merged in 2020-04, with the labels that each got.

#33 Update reducer 1 to implement 1
  src/reducer/database/helper/calendar.ts
  src/reducer/database/helper/general.ts
  src/reducer/database/models.ts
  src/reducer/database/osm/models.ts
  src/reducer/database/osm/statements/member.ts
  src/reducer/database/osm/statements/organization.ts
  src/reducer/database/osm/statements/platform.ts
  src/reducer/helper/profile.ts
  src/reducer/helper/statistic.ts
  src/reducer/index.ts
  src/utils/github/converter.ts
  src/utils/github/queries/data.ts
Labels: enhancement

#36 Add utils gitlab 1 to implement 1
  src/utils/gitlab/converter.ts
  src/utils/gitlab/index.ts
  src/utils/gitlab/paths.ts
Labels: enhancement

#38 Add oauth 1 to implement 1
  package.json
  src/toolbox/GuidGenerator.ts
  src/utils/oauth/GithubProvider.ts
  src/utils/oauth/config.json
  src/utils/oauth/index.ts
Labels: enhancement

#39 Add a Codacy badge to README.md
  README.md
Labels: documentation

#45 Intel quicky 1 to implement 1
  package.json
  src/index.ts
  src/reducer/database/helper/calendar.ts
  src/reducer/database/helper/general.ts
  src/reducer/database/osm/models.ts
  src/reducer/helper/profile.ts
  tsconfig.json
Labels: bug, enhancement
