Repository snek-at/intel, pull requests merged in 2020-06, with the labels that each got.

#47 README.md Update
  README.md
Labels: documentation

#76 Patch 1 to implement 1
  README.md
Labels: documentation

#77 Improve intel ba1 to implement 1
  .prettierrc
  .vscode/settings.json
  package.json
  src/index.ts
  src/utils/oauth/index.ts
  src/utils/talks/index.ts
  src/utils/upload/anonfiles.ts
Labels: enhancement

#81 Improve statistic aa1 to implement 1 (Fix invalid contribution type statistic)
  src/reducer/database/osm/models.ts
Labels: bug

#78 Implement 1 to master (v0.1.0)
  .gitignore
  .prettierrc
  .vscode/settings.json
  CONTRIBUTING.md
  README.md
  package.json
  public/index.html
  src/index.js
  src/index.ts
  src/reducer/database/helper/calendar.ts
  src/reducer/database/helper/general.ts
  src/reducer/database/helper/index.ts
  src/reducer/database/helper/statistic.ts
  src/reducer/database/models.ts
  src/reducer/database/osm/index.ts
  src/reducer/database/osm/models.ts
  src/reducer/database/osm/reconstructor.ts
  src/reducer/database/osm/statements/calendar.ts
  src/reducer/database/osm/statements/contribution.ts
  src/reducer/database/osm/statements/language.ts
  src/reducer/database/osm/statements/member.ts
  src/reducer/database/osm/statements/organization.ts
  src/reducer/database/osm/statements/organizationHasMember.ts
  src/reducer/database/osm/statements/platform.ts
  src/reducer/database/osm/statements/platformHasOrganization.ts
  src/reducer/database/osm/statements/platformHasRepository.ts
  src/reducer/database/osm/statements/repository.ts
  src/reducer/database/osm/statements/repositoryHasMember.ts
  src/reducer/database/osm/statements/statistic.ts
  src/reducer/database/osm/statements/streak.ts
  src/reducer/database/osm/statements/talk.ts
  src/reducer/helper/calendar.ts
  src/reducer/helper/index.ts
  src/reducer/helper/language.ts
  src/reducer/helper/profile.ts
  src/reducer/helper/statistic.ts
  src/reducer/helper/talks.ts
  src/reducer/index.ts
  src/toolbox/Delay.ts
  src/toolbox/GuidGenerator.ts
  src/utils/github/converter.ts
  src/utils/github/index.ts
  src/utils/github/queries/data.ts
  src/utils/github/queries/index.ts
  src/utils/gitlab/converter.ts
  src/utils/gitlab/index.ts
  src/utils/gitlab/paths.ts
  src/utils/oauth/GithubProvider.ts
  src/utils/oauth/config.json
  src/utils/oauth/index.ts
  src/utils/talks/converter.ts
  src/utils/talks/index.ts
  src/utils/talks/paths.ts
  src/utils/upload/anonfiles.ts
  src/utils/upload/index.ts
  tsconfig.json
Labels: documentation, enhancement

#87 Improve statistic ba1 to master (Bugfix: Calendar and Streaks)
  package.json
  src/reducer/database/helper/statistic.ts
  src/reducer/database/osm/statements/calendar.ts
Labels: bug, invalid
